package sys.model;
// Generated 5/03/2018 03:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer codCliente;
     private String nombres;
     private String apellidos;
     private String direccion;
     private String noRut;
     private String email;
     private int telefonoClaro;
     private int telefonoMovistar;
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public Cliente() {
    }

	
    public Cliente(String nombres, String apellidos, String direccion, String noRut, String email, int telefonoClaro, int telefonoMovistar) {
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.direccion = direccion;
        this.noRut = noRut;
        this.email = email;
        this.telefonoClaro = telefonoClaro;
        this.telefonoMovistar = telefonoMovistar;
    }
    public Cliente(String nombres, String apellidos, String direccion, String noRut, String email, int telefonoClaro, int telefonoMovistar, Set<Factura> facturas) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.noRut = noRut;
       this.email = email;
       this.telefonoClaro = telefonoClaro;
       this.telefonoMovistar = telefonoMovistar;
       this.facturas = facturas;
    }
   
    public Integer getCodCliente() {
        return this.codCliente;
    }
    
    public void setCodCliente(Integer codCliente) {
        this.codCliente = codCliente;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNoRut() {
        return this.noRut;
    }
    
    public void setNoRut(String noRut) {
        this.noRut = noRut;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getTelefonoClaro() {
        return this.telefonoClaro;
    }
    
    public void setTelefonoClaro(int telefonoClaro) {
        this.telefonoClaro = telefonoClaro;
    }
    public int getTelefonoMovistar() {
        return this.telefonoMovistar;
    }
    
    public void setTelefonoMovistar(int telefonoMovistar) {
        this.telefonoMovistar = telefonoMovistar;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


