package sys.model;
// Generated 5/03/2018 03:34:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cotizacion generated by hbm2java
 */
public class Cotizacion  implements java.io.Serializable {


     private int idCotizacion;
     private Vendedor vendedorByIdEmpleado;
     private Vendedor vendedorByIdCliente;
     private Date fecha;
     private long granTotal;
     private Set<DetalleCotizacion> detalleCotizacions = new HashSet<DetalleCotizacion>(0);

    public Cotizacion() {
    }

	
    public Cotizacion(int idCotizacion, Vendedor vendedorByIdEmpleado, Vendedor vendedorByIdCliente, Date fecha, long granTotal) {
        this.idCotizacion = idCotizacion;
        this.vendedorByIdEmpleado = vendedorByIdEmpleado;
        this.vendedorByIdCliente = vendedorByIdCliente;
        this.fecha = fecha;
        this.granTotal = granTotal;
    }
    public Cotizacion(int idCotizacion, Vendedor vendedorByIdEmpleado, Vendedor vendedorByIdCliente, Date fecha, long granTotal, Set<DetalleCotizacion> detalleCotizacions) {
       this.idCotizacion = idCotizacion;
       this.vendedorByIdEmpleado = vendedorByIdEmpleado;
       this.vendedorByIdCliente = vendedorByIdCliente;
       this.fecha = fecha;
       this.granTotal = granTotal;
       this.detalleCotizacions = detalleCotizacions;
    }
   
    public int getIdCotizacion() {
        return this.idCotizacion;
    }
    
    public void setIdCotizacion(int idCotizacion) {
        this.idCotizacion = idCotizacion;
    }
    public Vendedor getVendedorByIdEmpleado() {
        return this.vendedorByIdEmpleado;
    }
    
    public void setVendedorByIdEmpleado(Vendedor vendedorByIdEmpleado) {
        this.vendedorByIdEmpleado = vendedorByIdEmpleado;
    }
    public Vendedor getVendedorByIdCliente() {
        return this.vendedorByIdCliente;
    }
    
    public void setVendedorByIdCliente(Vendedor vendedorByIdCliente) {
        this.vendedorByIdCliente = vendedorByIdCliente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public long getGranTotal() {
        return this.granTotal;
    }
    
    public void setGranTotal(long granTotal) {
        this.granTotal = granTotal;
    }
    public Set<DetalleCotizacion> getDetalleCotizacions() {
        return this.detalleCotizacions;
    }
    
    public void setDetalleCotizacions(Set<DetalleCotizacion> detalleCotizacions) {
        this.detalleCotizacions = detalleCotizacions;
    }




}


