package sys.model;
// Generated 5/03/2018 03:34:31 PM by Hibernate Tools 4.3.1



/**
 * DetalleCotizacion generated by hbm2java
 */
public class DetalleCotizacion  implements java.io.Serializable {


     private int idDetalleCotizacion;
     private Cotizacion cotizacion;
     private Producto producto;
     private int cantidad;
     private long precioUnitario;
     private long total;

    public DetalleCotizacion() {
    }

    public DetalleCotizacion(int idDetalleCotizacion, Cotizacion cotizacion, Producto producto, int cantidad, long precioUnitario, long total) {
       this.idDetalleCotizacion = idDetalleCotizacion;
       this.cotizacion = cotizacion;
       this.producto = producto;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
       this.total = total;
    }
   
    public int getIdDetalleCotizacion() {
        return this.idDetalleCotizacion;
    }
    
    public void setIdDetalleCotizacion(int idDetalleCotizacion) {
        this.idDetalleCotizacion = idDetalleCotizacion;
    }
    public Cotizacion getCotizacion() {
        return this.cotizacion;
    }
    
    public void setCotizacion(Cotizacion cotizacion) {
        this.cotizacion = cotizacion;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public long getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(long precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public long getTotal() {
        return this.total;
    }
    
    public void setTotal(long total) {
        this.total = total;
    }




}


