package sys.model;
// Generated 5/03/2018 03:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer codProducto;
     private TallaBalonBasket tallaBalonBasket;
     private TallaBalonFoot tallaBalonFoot;
     private TallaCamisola tallaCamisola;
     private TallaChumpa tallaChumpa;
     private TallaEspinillera tallaEspinillera;
     private TallaLicra tallaLicra;
     private TallaPantaloneta tallaPantaloneta;
     private TallaPescador tallaPescador;
     private TallaZapatilla tallaZapatilla;
     private TipoZapatilla tipoZapatilla;
     private String nombreProducto;
     private long precioVenta;
     private long precioCosto;
     private long margenGanancia;
     private int stocMinimo;
     private int stocActual;
     private String codBarra;
     private Set<Detallefactura> detallefacturas = new HashSet<Detallefactura>(0);
     private Set<DetalleCotizacion> detalleCotizacions = new HashSet<DetalleCotizacion>(0);

    public Producto() {
    }

	
    public Producto(String nombreProducto, long precioVenta, long precioCosto, long margenGanancia, int stocMinimo, int stocActual, String codBarra) {
        this.nombreProducto = nombreProducto;
        this.precioVenta = precioVenta;
        this.precioCosto = precioCosto;
        this.margenGanancia = margenGanancia;
        this.stocMinimo = stocMinimo;
        this.stocActual = stocActual;
        this.codBarra = codBarra;
    }
    public Producto(TallaBalonBasket tallaBalonBasket, TallaBalonFoot tallaBalonFoot, TallaCamisola tallaCamisola, TallaChumpa tallaChumpa, TallaEspinillera tallaEspinillera, TallaLicra tallaLicra, TallaPantaloneta tallaPantaloneta, TallaPescador tallaPescador, TallaZapatilla tallaZapatilla, TipoZapatilla tipoZapatilla, String nombreProducto, long precioVenta, long precioCosto, long margenGanancia, int stocMinimo, int stocActual, String codBarra, Set<Detallefactura> detallefacturas, Set<DetalleCotizacion> detalleCotizacions) {
       this.tallaBalonBasket = tallaBalonBasket;
       this.tallaBalonFoot = tallaBalonFoot;
       this.tallaCamisola = tallaCamisola;
       this.tallaChumpa = tallaChumpa;
       this.tallaEspinillera = tallaEspinillera;
       this.tallaLicra = tallaLicra;
       this.tallaPantaloneta = tallaPantaloneta;
       this.tallaPescador = tallaPescador;
       this.tallaZapatilla = tallaZapatilla;
       this.tipoZapatilla = tipoZapatilla;
       this.nombreProducto = nombreProducto;
       this.precioVenta = precioVenta;
       this.precioCosto = precioCosto;
       this.margenGanancia = margenGanancia;
       this.stocMinimo = stocMinimo;
       this.stocActual = stocActual;
       this.codBarra = codBarra;
       this.detallefacturas = detallefacturas;
       this.detalleCotizacions = detalleCotizacions;
    }
   
    public Integer getCodProducto() {
        return this.codProducto;
    }
    
    public void setCodProducto(Integer codProducto) {
        this.codProducto = codProducto;
    }
    public TallaBalonBasket getTallaBalonBasket() {
        return this.tallaBalonBasket;
    }
    
    public void setTallaBalonBasket(TallaBalonBasket tallaBalonBasket) {
        this.tallaBalonBasket = tallaBalonBasket;
    }
    public TallaBalonFoot getTallaBalonFoot() {
        return this.tallaBalonFoot;
    }
    
    public void setTallaBalonFoot(TallaBalonFoot tallaBalonFoot) {
        this.tallaBalonFoot = tallaBalonFoot;
    }
    public TallaCamisola getTallaCamisola() {
        return this.tallaCamisola;
    }
    
    public void setTallaCamisola(TallaCamisola tallaCamisola) {
        this.tallaCamisola = tallaCamisola;
    }
    public TallaChumpa getTallaChumpa() {
        return this.tallaChumpa;
    }
    
    public void setTallaChumpa(TallaChumpa tallaChumpa) {
        this.tallaChumpa = tallaChumpa;
    }
    public TallaEspinillera getTallaEspinillera() {
        return this.tallaEspinillera;
    }
    
    public void setTallaEspinillera(TallaEspinillera tallaEspinillera) {
        this.tallaEspinillera = tallaEspinillera;
    }
    public TallaLicra getTallaLicra() {
        return this.tallaLicra;
    }
    
    public void setTallaLicra(TallaLicra tallaLicra) {
        this.tallaLicra = tallaLicra;
    }
    public TallaPantaloneta getTallaPantaloneta() {
        return this.tallaPantaloneta;
    }
    
    public void setTallaPantaloneta(TallaPantaloneta tallaPantaloneta) {
        this.tallaPantaloneta = tallaPantaloneta;
    }
    public TallaPescador getTallaPescador() {
        return this.tallaPescador;
    }
    
    public void setTallaPescador(TallaPescador tallaPescador) {
        this.tallaPescador = tallaPescador;
    }
    public TallaZapatilla getTallaZapatilla() {
        return this.tallaZapatilla;
    }
    
    public void setTallaZapatilla(TallaZapatilla tallaZapatilla) {
        this.tallaZapatilla = tallaZapatilla;
    }
    public TipoZapatilla getTipoZapatilla() {
        return this.tipoZapatilla;
    }
    
    public void setTipoZapatilla(TipoZapatilla tipoZapatilla) {
        this.tipoZapatilla = tipoZapatilla;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public long getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(long precioVenta) {
        this.precioVenta = precioVenta;
    }
    public long getPrecioCosto() {
        return this.precioCosto;
    }
    
    public void setPrecioCosto(long precioCosto) {
        this.precioCosto = precioCosto;
    }
    public long getMargenGanancia() {
        return this.margenGanancia;
    }
    
    public void setMargenGanancia(long margenGanancia) {
        this.margenGanancia = margenGanancia;
    }
    public int getStocMinimo() {
        return this.stocMinimo;
    }
    
    public void setStocMinimo(int stocMinimo) {
        this.stocMinimo = stocMinimo;
    }
    public int getStocActual() {
        return this.stocActual;
    }
    
    public void setStocActual(int stocActual) {
        this.stocActual = stocActual;
    }
    public String getCodBarra() {
        return this.codBarra;
    }
    
    public void setCodBarra(String codBarra) {
        this.codBarra = codBarra;
    }
    public Set<Detallefactura> getDetallefacturas() {
        return this.detallefacturas;
    }
    
    public void setDetallefacturas(Set<Detallefactura> detallefacturas) {
        this.detallefacturas = detallefacturas;
    }
    public Set<DetalleCotizacion> getDetalleCotizacions() {
        return this.detalleCotizacions;
    }
    
    public void setDetalleCotizacions(Set<DetalleCotizacion> detalleCotizacions) {
        this.detalleCotizacions = detalleCotizacions;
    }




}


