package sys.model;
// Generated 5/03/2018 03:34:31 PM by Hibernate Tools 4.3.1



/**
 * Sucursal generated by hbm2java
 */
public class Sucursal  implements java.io.Serializable {


     private int idSucursal;
     private Vendedor vendedor;
     private String direccion;
     private int nombreSucursal;
     private int telClaro;
     private int telMovistar;
     private String email;

    public Sucursal() {
    }

    public Sucursal(int idSucursal, Vendedor vendedor, String direccion, int nombreSucursal, int telClaro, int telMovistar, String email) {
       this.idSucursal = idSucursal;
       this.vendedor = vendedor;
       this.direccion = direccion;
       this.nombreSucursal = nombreSucursal;
       this.telClaro = telClaro;
       this.telMovistar = telMovistar;
       this.email = email;
    }
   
    public int getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(int idSucursal) {
        this.idSucursal = idSucursal;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getNombreSucursal() {
        return this.nombreSucursal;
    }
    
    public void setNombreSucursal(int nombreSucursal) {
        this.nombreSucursal = nombreSucursal;
    }
    public int getTelClaro() {
        return this.telClaro;
    }
    
    public void setTelClaro(int telClaro) {
        this.telClaro = telClaro;
    }
    public int getTelMovistar() {
        return this.telMovistar;
    }
    
    public void setTelMovistar(int telMovistar) {
        this.telMovistar = telMovistar;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


