package sys.model;
// Generated 5/03/2018 03:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TallaZapatilla generated by hbm2java
 */
public class TallaZapatilla  implements java.io.Serializable {


     private int idTallaZapatilla;
     private String nombreTallaZapatilla;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public TallaZapatilla() {
    }

	
    public TallaZapatilla(int idTallaZapatilla, String nombreTallaZapatilla) {
        this.idTallaZapatilla = idTallaZapatilla;
        this.nombreTallaZapatilla = nombreTallaZapatilla;
    }
    public TallaZapatilla(int idTallaZapatilla, String nombreTallaZapatilla, Set<Producto> productos) {
       this.idTallaZapatilla = idTallaZapatilla;
       this.nombreTallaZapatilla = nombreTallaZapatilla;
       this.productos = productos;
    }
   
    public int getIdTallaZapatilla() {
        return this.idTallaZapatilla;
    }
    
    public void setIdTallaZapatilla(int idTallaZapatilla) {
        this.idTallaZapatilla = idTallaZapatilla;
    }
    public String getNombreTallaZapatilla() {
        return this.nombreTallaZapatilla;
    }
    
    public void setNombreTallaZapatilla(String nombreTallaZapatilla) {
        this.nombreTallaZapatilla = nombreTallaZapatilla;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


