package sys.model;
// Generated 5/03/2018 03:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TallaEspinillera generated by hbm2java
 */
public class TallaEspinillera  implements java.io.Serializable {


     private int idTallaEspinillera;
     private String nombreTallaEspinillera;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public TallaEspinillera() {
    }

	
    public TallaEspinillera(int idTallaEspinillera, String nombreTallaEspinillera) {
        this.idTallaEspinillera = idTallaEspinillera;
        this.nombreTallaEspinillera = nombreTallaEspinillera;
    }
    public TallaEspinillera(int idTallaEspinillera, String nombreTallaEspinillera, Set<Producto> productos) {
       this.idTallaEspinillera = idTallaEspinillera;
       this.nombreTallaEspinillera = nombreTallaEspinillera;
       this.productos = productos;
    }
   
    public int getIdTallaEspinillera() {
        return this.idTallaEspinillera;
    }
    
    public void setIdTallaEspinillera(int idTallaEspinillera) {
        this.idTallaEspinillera = idTallaEspinillera;
    }
    public String getNombreTallaEspinillera() {
        return this.nombreTallaEspinillera;
    }
    
    public void setNombreTallaEspinillera(String nombreTallaEspinillera) {
        this.nombreTallaEspinillera = nombreTallaEspinillera;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


