package sys.model;
// Generated 5/03/2018 03:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TallaPescador generated by hbm2java
 */
public class TallaPescador  implements java.io.Serializable {


     private int idTallaPescador;
     private String nombreTallaPescador;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public TallaPescador() {
    }

	
    public TallaPescador(int idTallaPescador, String nombreTallaPescador) {
        this.idTallaPescador = idTallaPescador;
        this.nombreTallaPescador = nombreTallaPescador;
    }
    public TallaPescador(int idTallaPescador, String nombreTallaPescador, Set<Producto> productos) {
       this.idTallaPescador = idTallaPescador;
       this.nombreTallaPescador = nombreTallaPescador;
       this.productos = productos;
    }
   
    public int getIdTallaPescador() {
        return this.idTallaPescador;
    }
    
    public void setIdTallaPescador(int idTallaPescador) {
        this.idTallaPescador = idTallaPescador;
    }
    public String getNombreTallaPescador() {
        return this.nombreTallaPescador;
    }
    
    public void setNombreTallaPescador(String nombreTallaPescador) {
        this.nombreTallaPescador = nombreTallaPescador;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


