package sys.model;
// Generated 5/03/2018 03:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TallaCamisola generated by hbm2java
 */
public class TallaCamisola  implements java.io.Serializable {


     private int idTallaCamisola;
     private String nombreTallaCamisola;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public TallaCamisola() {
    }

	
    public TallaCamisola(int idTallaCamisola, String nombreTallaCamisola) {
        this.idTallaCamisola = idTallaCamisola;
        this.nombreTallaCamisola = nombreTallaCamisola;
    }
    public TallaCamisola(int idTallaCamisola, String nombreTallaCamisola, Set<Producto> productos) {
       this.idTallaCamisola = idTallaCamisola;
       this.nombreTallaCamisola = nombreTallaCamisola;
       this.productos = productos;
    }
   
    public int getIdTallaCamisola() {
        return this.idTallaCamisola;
    }
    
    public void setIdTallaCamisola(int idTallaCamisola) {
        this.idTallaCamisola = idTallaCamisola;
    }
    public String getNombreTallaCamisola() {
        return this.nombreTallaCamisola;
    }
    
    public void setNombreTallaCamisola(String nombreTallaCamisola) {
        this.nombreTallaCamisola = nombreTallaCamisola;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


