package sys.model;
// Generated 5/03/2018 03:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TallaBalonFoot generated by hbm2java
 */
public class TallaBalonFoot  implements java.io.Serializable {


     private int idTallaBalonFut;
     private String nombreTallaBalonFut;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public TallaBalonFoot() {
    }

	
    public TallaBalonFoot(int idTallaBalonFut, String nombreTallaBalonFut) {
        this.idTallaBalonFut = idTallaBalonFut;
        this.nombreTallaBalonFut = nombreTallaBalonFut;
    }
    public TallaBalonFoot(int idTallaBalonFut, String nombreTallaBalonFut, Set<Producto> productos) {
       this.idTallaBalonFut = idTallaBalonFut;
       this.nombreTallaBalonFut = nombreTallaBalonFut;
       this.productos = productos;
    }
   
    public int getIdTallaBalonFut() {
        return this.idTallaBalonFut;
    }
    
    public void setIdTallaBalonFut(int idTallaBalonFut) {
        this.idTallaBalonFut = idTallaBalonFut;
    }
    public String getNombreTallaBalonFut() {
        return this.nombreTallaBalonFut;
    }
    
    public void setNombreTallaBalonFut(String nombreTallaBalonFut) {
        this.nombreTallaBalonFut = nombreTallaBalonFut;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


