package sys.model;
// Generated 5/03/2018 03:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TallaChumpa generated by hbm2java
 */
public class TallaChumpa  implements java.io.Serializable {


     private int idTallaChumpa;
     private String nombreTallaChumpa;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public TallaChumpa() {
    }

	
    public TallaChumpa(int idTallaChumpa, String nombreTallaChumpa) {
        this.idTallaChumpa = idTallaChumpa;
        this.nombreTallaChumpa = nombreTallaChumpa;
    }
    public TallaChumpa(int idTallaChumpa, String nombreTallaChumpa, Set<Producto> productos) {
       this.idTallaChumpa = idTallaChumpa;
       this.nombreTallaChumpa = nombreTallaChumpa;
       this.productos = productos;
    }
   
    public int getIdTallaChumpa() {
        return this.idTallaChumpa;
    }
    
    public void setIdTallaChumpa(int idTallaChumpa) {
        this.idTallaChumpa = idTallaChumpa;
    }
    public String getNombreTallaChumpa() {
        return this.nombreTallaChumpa;
    }
    
    public void setNombreTallaChumpa(String nombreTallaChumpa) {
        this.nombreTallaChumpa = nombreTallaChumpa;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


