package sys.model;
// Generated 5/03/2018 03:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TallaPantaloneta generated by hbm2java
 */
public class TallaPantaloneta  implements java.io.Serializable {


     private int idTallaPantaloneta;
     private String nombreTallaPantaloneta;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public TallaPantaloneta() {
    }

	
    public TallaPantaloneta(int idTallaPantaloneta, String nombreTallaPantaloneta) {
        this.idTallaPantaloneta = idTallaPantaloneta;
        this.nombreTallaPantaloneta = nombreTallaPantaloneta;
    }
    public TallaPantaloneta(int idTallaPantaloneta, String nombreTallaPantaloneta, Set<Producto> productos) {
       this.idTallaPantaloneta = idTallaPantaloneta;
       this.nombreTallaPantaloneta = nombreTallaPantaloneta;
       this.productos = productos;
    }
   
    public int getIdTallaPantaloneta() {
        return this.idTallaPantaloneta;
    }
    
    public void setIdTallaPantaloneta(int idTallaPantaloneta) {
        this.idTallaPantaloneta = idTallaPantaloneta;
    }
    public String getNombreTallaPantaloneta() {
        return this.nombreTallaPantaloneta;
    }
    
    public void setNombreTallaPantaloneta(String nombreTallaPantaloneta) {
        this.nombreTallaPantaloneta = nombreTallaPantaloneta;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


