package sys.model;
// Generated 5/03/2018 03:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TallaBalonBasket generated by hbm2java
 */
public class TallaBalonBasket  implements java.io.Serializable {


     private int idTallaBalonBasket;
     private String nombreTallaBalonBasket;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public TallaBalonBasket() {
    }

	
    public TallaBalonBasket(int idTallaBalonBasket, String nombreTallaBalonBasket) {
        this.idTallaBalonBasket = idTallaBalonBasket;
        this.nombreTallaBalonBasket = nombreTallaBalonBasket;
    }
    public TallaBalonBasket(int idTallaBalonBasket, String nombreTallaBalonBasket, Set<Producto> productos) {
       this.idTallaBalonBasket = idTallaBalonBasket;
       this.nombreTallaBalonBasket = nombreTallaBalonBasket;
       this.productos = productos;
    }
   
    public int getIdTallaBalonBasket() {
        return this.idTallaBalonBasket;
    }
    
    public void setIdTallaBalonBasket(int idTallaBalonBasket) {
        this.idTallaBalonBasket = idTallaBalonBasket;
    }
    public String getNombreTallaBalonBasket() {
        return this.nombreTallaBalonBasket;
    }
    
    public void setNombreTallaBalonBasket(String nombreTallaBalonBasket) {
        this.nombreTallaBalonBasket = nombreTallaBalonBasket;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


