package sys.model;
// Generated 5/03/2018 03:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TallaLicra generated by hbm2java
 */
public class TallaLicra  implements java.io.Serializable {


     private int idTallaLicra;
     private String nombreTallaLicra;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public TallaLicra() {
    }

	
    public TallaLicra(int idTallaLicra, String nombreTallaLicra) {
        this.idTallaLicra = idTallaLicra;
        this.nombreTallaLicra = nombreTallaLicra;
    }
    public TallaLicra(int idTallaLicra, String nombreTallaLicra, Set<Producto> productos) {
       this.idTallaLicra = idTallaLicra;
       this.nombreTallaLicra = nombreTallaLicra;
       this.productos = productos;
    }
   
    public int getIdTallaLicra() {
        return this.idTallaLicra;
    }
    
    public void setIdTallaLicra(int idTallaLicra) {
        this.idTallaLicra = idTallaLicra;
    }
    public String getNombreTallaLicra() {
        return this.nombreTallaLicra;
    }
    
    public void setNombreTallaLicra(String nombreTallaLicra) {
        this.nombreTallaLicra = nombreTallaLicra;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


