package sys.model;
// Generated 5/03/2018 03:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoZapatilla generated by hbm2java
 */
public class TipoZapatilla  implements java.io.Serializable {


     private int idTipoZapatilla;
     private String nombreTipoZapatilla;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public TipoZapatilla() {
    }

	
    public TipoZapatilla(int idTipoZapatilla, String nombreTipoZapatilla) {
        this.idTipoZapatilla = idTipoZapatilla;
        this.nombreTipoZapatilla = nombreTipoZapatilla;
    }
    public TipoZapatilla(int idTipoZapatilla, String nombreTipoZapatilla, Set<Producto> productos) {
       this.idTipoZapatilla = idTipoZapatilla;
       this.nombreTipoZapatilla = nombreTipoZapatilla;
       this.productos = productos;
    }
   
    public int getIdTipoZapatilla() {
        return this.idTipoZapatilla;
    }
    
    public void setIdTipoZapatilla(int idTipoZapatilla) {
        this.idTipoZapatilla = idTipoZapatilla;
    }
    public String getNombreTipoZapatilla() {
        return this.nombreTipoZapatilla;
    }
    
    public void setNombreTipoZapatilla(String nombreTipoZapatilla) {
        this.nombreTipoZapatilla = nombreTipoZapatilla;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


